### ISSUE TITLE
Add support to create  "metric" as a istio resource

### ISSUE THREAD

**Issue by anmolbabu** [snowdrop/istio-java-api#13] opened 2018-05-07 15:20 UTC
When I try to create a metric as in https://github.com/anmolbabu/hdd-istio-java-poc,
it fails with the following error:

java.lang.IllegalArgumentException: metric is not a known Istio resource.
	at me.snowdrop.istio.client.IstioClient.registerCustomResources(IstioClient.java:50)
	at me.snowdrop.istio.client.IstioClient.registerCustomResources(IstioClient.java:72)
	at org.osio.hdd.istio.com.App.main(App.java:44)

On some debugging, I found that it was failing at:
https://github.com/snowdrop/istio-java-api/blob/master/istio-common/src/main/java/me/snowdrop/istio/api/internal/IstioSpecRegistry.java#L78 as it seems from https://github.com/snowdrop/istio-java-api/blob/master/istio-common/src/main/java/me/snowdrop/istio/api/internal/IstioSpecRegistry.java#L45-L47 that the type "metric" is not supported.

Note: The metric I am trying to create is the same as in the istio tutorial @ https://github.com/redhat-developer-demos/istio-tutorial#custom-metrics

**Comment by metacosm** [comment] 2018-05-07 15:40
Indeed, this isn't currently supported but I will add support for it as soon as possible. Thanks for the report!

**Comment by bgokden** [comment] 2018-05-07 15:41
@anmolbabu We had a similar issue we end up adding our MixerMetric Structure and Prometheus Structure.

https://github.com/magneticio/istio-java-api/tree/master/istio-model/src/main/java/me/snowdrop/istio/api/model/v1/mixer/template

We didn't test it well enough. If it passes our tests, we will create a pull request.

**Comment by metacosm** [comment] 2018-05-07 15:48
@bgokden Thank you! This project is still in its infancy and figuring out which resources need to be generated is not as straightforward as it should be… but we'll get there in time! :)

**Comment by anmolbabu** [comment] 2018-05-08 03:06
Also please add support for more resource types like prometheus and rule as in the example @ https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/recommendation_requestcount.yml

**Comment by metacosm** [comment] 2018-05-09 15:11
I have started working on this. I hope to have a fix by the end of the week. By the way, @anmolbabu, you should definitely use the latest version: we're up to `0.9`, you're still using `0.7`. I need to figure out what versioning scheme to adopt since it'd be nice that the lib match the Istio version it is compatible with.

**Comment by anmolbabu** [comment] 2018-05-10 11:04
Could you please also add "kind: prometheus" as in https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/recommendation_requestcount.yml#L16 and "kind: rule" as in https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/recommendation_requestcount.yml#L32

**Comment by metacosm** [comment] 2018-05-10 13:15
Yes, it’s planned

**Comment by metacosm** [comment] 2018-05-11 19:55
BTW, @anmolbabu are these files confirmed to work on Istio 0.7.1 because the documentation (https://istio.io/docs/reference/config/adapters/prometheus.html) states that, for example, https://github.com/redhat-developer-demos/istio-tutorial/blob/master/istiofiles/recommendation_requestcount.yml#L23 should be `instanceName` and not `instance_name`?

**Comment by anmolbabu** [comment] 2018-05-17 10:45
@metacosm Yes I tried https://istio.io/docs/tasks/telemetry/metrics-logs.html#collecting-new-telemetry-data on istio-0.7.1 and instance_name still works

**Comment by metacosm** [comment] 2018-05-17 10:50
@anmolbabu actually, based on what I've learned since I asked the question, it works because the Istio parser is lenient and accepts both versions. However, field names are supposed to use lowerCamelCase. Supporting both in the Java API, while possible, would make things more complex so right now, I tend to think that I will only support the lowerCamelCase format (i.e. `instanceName`). What do you think?

**Comment by anmolbabu** [comment] 2018-05-17 12:44
@metacosm I'll give this("_" notation/snake case replaced with camel case) a try on my deployment and confirm max by tomorrow EOD

**Comment by anmolbabu** [comment] 2018-05-18 12:03
@metacosm You are right, the camel case works

**Comment by metacosm** [comment] 2018-06-15 09:33
This has been fixed with the `0.10` version released yesterday.

**Closed by metacosm** 2018-06-15 09:33 UTC
